plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
    id("com.gradleup.shadow") version "9.2.2"
}

def nmsVersions = [
        nmsV121R1: [path: 'v1_21_R1', dependency: '1.21.1-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV121R2: [path: 'v1_21_R2', dependency: '1.21.3-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV121R3: [path: 'v1_21_R3', dependency: '1.21.4-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV121R4: [path: 'v1_21_R4', dependency: '1.21.5-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV121R5: [path: 'v1_21_R5', dependency: '1.21.8-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV121R6: [path: 'v1_21_R6', dependency: '1.21.10-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV121R7: [path: 'v1_21_R7', dependency: '1.21.11-R0.1-SNAPSHOT', classifier: 'remapped-mojang'],
        nmsV261R1: [path: 'v26_1_R1', dependency: '26.1.2-R0.1-SNAPSHOT', javaVersion: 25],
        nmsV262R1: [path: 'v26_2_R1', dependency: '26.2-R0.1-SNAPSHOT', javaVersion: 25],
]

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "codemc-nms"
        url = "https://repo.codemc.io/repository/nms/"
    }
    maven {
        name = "xenondevsReleases"
        url = "https://repo.xenondevs.xyz/releases"
    }
    maven {
        url = "https://repo.momirealms.net/releases/"
    }
    maven {
        url = "https://repo.momirealms.net/snapshots/"
    }
    maven {
        name = "placeholderapi"
        url = "https://repo.extendedclip.com/releases/"
    }
}

nmsVersions.each { sourceSetName, version ->
    sourceSets.create(sourceSetName) {
        java.srcDir("src/nms/${version.path}/java")
        compileClasspath += sourceSets.main.output
        runtimeClasspath += output + compileClasspath
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    compileOnly("net.momirealms:craft-engine-bukkit:26.7.4")
    compileOnly("net.momirealms:craft-engine-core:26.7.4")
    compileOnly("net.momirealms:craft-engine-adventure:26.7.4")
    compileOnly("net.momirealms:craft-engine-bukkit-proxy:26.7.4")
    compileOnly("net.momirealms:craft-engine-nms-helper-mojmap:1.0.213")
    compileOnly("net.momirealms:craft-engine-nms-helper:1.0.213")
    compileOnly("io.netty:netty-all:4.1.100.Final")
    compileOnly("com.mojang:datafixerupper:8.0.16")
    compileOnly("net.momirealms:sparrow-util:0.112")
    compileOnly("net.momirealms:sparrow-nbt:0.18.8")
    compileOnly("net.momirealms:sparrow-nbt-legacy-codec:0.18.8")
    compileOnly("net.momirealms:sparrow-nbt-codec:0.18.4")
    compileOnly("net.momirealms:sparrow-nbt-adventure:0.18.4")
    compileOnly("net.momirealms:sparrow-heart:0.69")
    compileOnly("net.momirealms:sparrow-metadata:1.13")
    compileOnly("net.momirealms:sparrow-reflection:0.31")
    compileOnly("net.momirealms:sparrow-reflection-proxy-scanner:1.1")
    compileOnly("me.clip:placeholderapi:2.11.6")
    implementation("net.momirealms:antigrieflib:1.0.11")
    implementation("org.bstats:bstats-bukkit:3.2.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testImplementation("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    testImplementation("net.momirealms:craft-engine-core:26.7.4")
    testImplementation("it.unimi.dsi:fastutil:8.5.18")
    testImplementation("com.google.guava:guava:33.6.0-jre")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.4")

    nmsVersions.each { sourceSetName, version ->
        def notation = "org.spigotmc:spigot:${version.dependency}"
        if (version.classifier != null) {
            notation += ":${version.classifier}"
        }
        add("${sourceSetName}CompileOnly", notation)
    }
}

shadowJar {
    archiveClassifier.set('')
    from(nmsVersions.keySet().collect { sourceSets.named(it).get().output })
    relocate 'net.momirealms.antigrieflib', 'net.kaleidoscope.cookery.libs.antigrieflib'
    relocate 'org.bstats', 'net.kaleidoscope.cookery.libs.bstats'
}

jar {
    enabled = false
}

tasks.named('assemble') {
    dependsOn(tasks.named('shadowJar'))
    dependsOn('javadocJar')
}

tasks {
    runServer {
        minecraftVersion("26.1.2")
    }
}

java {
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}

tasks.named('test') {
    useJUnitPlatform()
}

nmsVersions.each { sourceSetName, version ->
    if (version.javaVersion != null) {
        tasks.named(sourceSets[sourceSetName].compileJavaTaskName, JavaCompile) {
            options.release.set(21)
            javaCompiler.set(javaToolchains.compilerFor {
                languageVersion = JavaLanguageVersion.of(version.javaVersion)
            })
        }
    }
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
    options.addBooleanOption('Xdoclint:none', true)
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
